baseURL = "https://ngs.io/"
ignoreLogs = ['warning-goldmark-raw-html']
languageCode = "en"
title = "Atsushi Nagase"

[module]
[[module.imports]]
path = "go.ngs.io/hugo-primer-blog"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[permalinks]
posts = "/:year/:month/:day/:slug/"

[taxonomies]
archive = "archives"
tag = "tags"

[params]
author = "Atsushi Nagase"
defaultTheme = "auto"
description = "Blog by Atsushi Nagase"
googleAnalyticsID = "G-D8FYDEZWPK"
showAuthor = true
showReadingTime = true
faviconPng = "favicon.png"

[[params.appleTouchIcons]]
sizes = "152x152"
href = "apple-touch-icon-152x152-precomposed.png"
[[params.appleTouchIcons]]
sizes = "144x144"
href = "apple-touch-icon-144x144-precomposed.png"
[[params.appleTouchIcons]]
sizes = "120x120"
href = "apple-touch-icon-120x120-precomposed.png"
[[params.appleTouchIcons]]
sizes = "114x114"
href = "apple-touch-icon-114x114-precomposed.png"
[[params.appleTouchIcons]]
sizes = "76x76"
href = "apple-touch-icon-76x76-precomposed.png"
[[params.appleTouchIcons]]
sizes = "72x72"
href = "apple-touch-icon-72x72-precomposed.png"
[[params.appleTouchIcons]]
sizes = "60x60"
href = "apple-touch-icon-60x60-precomposed.png"
[[params.appleTouchIcons]]
href = "apple-touch-icon-precomposed.png"

[[params.sidebarModules]]
partial = "links"

[[params.sidebarModules]]
partial = "recentPosts"

[[params.sidebarModules]]
partial = "archive"

[[params.sidebarModules]]
partial = "tags"

[params.social]
bluesky = "ngs.io"
github = "ngs"
x = "ngs"

[[menus.main]]
name = "Home"
pageRef = "/"
weight = 10

[[menus.main]]
name = "About"
pageRef = "/about"
weight = 20

[[menus.main]]
name = "ブログ (日本語)"
url = "https://ja.ngs.io/"
weight = 30
