baseURL = "https://ngs.io/"
ignoreLogs = ['warning-goldmark-raw-html']
languageCode = "en"
title = "Atsushi Nagase"

[module]
[[module.imports]]
path = "go.ngs.io/hugo-primer-blog"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[permalinks]
posts = "/:year/:month/:day/:slug/"

[taxonomies]
archive = "archives"
tag = "tags"

[params]
author = "Atsushi Nagase"
defaultTheme = "auto"
description = "Blog by Atsushi Nagase"
googleAnalyticsID = "G-D8FYDEZWPK"
showAuthor = true
showReadingTime = true

[[params.sidebarModules]]
partial = "links"

[[params.sidebarModules]]
partial = "recentPosts"

[[params.sidebarModules]]
partial = "archive"

[[params.sidebarModules]]
partial = "tags"

[params.social]
bluesky = "ngs.io"
github = "ngs"
x = "ngs"

[[menus.main]]
name = "Home"
pageRef = "/"
weight = 10

[[menus.main]]
name = "About"
pageRef = "/about"
weight = 20

[[menus.main]]
name = "ブログ (日本語)"
url = "https://ja.ngs.io/"
weight = 30
